### ISSUE TITLE
Build fails on 75.0.3770.80-1.1 tag

### ISSUE THREAD

**Issue by IvanTrendafilov** [ungoogled-software/ungoogled-chromium-macos#14]
```
INFO: Unpacking "chromium" to ./ ...
DEBUG: Using BSD or GNU tar extractor
DEBUG: tar command line: /usr/bin/tar -xf /Users/fusion/git/ungoogled-chromium-macos/build/download_cache/chromium-75.0.3770.80.tar.xz -C /Users/fusion/git/ungoogled-chromium-macos/build/src
INFO: Unpacking "google-toolbox-for-mac" to third_party/google_toolbox_for_mac/src ...
DEBUG: Using BSD or GNU tar extractor
DEBUG: tar command line: /usr/bin/tar -xf /Users/fusion/git/ungoogled-chromium-macos/build/download_cache/google-toolbox-for-mac-v2.2.1.tar.gz -C /Users/fusion/git/ungoogled-chromium-macos/build/src/third_party/google_toolbox_for_mac/src
ERROR: Could not find relative_to directory in extracted files: google-toolbox-for-mac-v2.2.1
Traceback (most recent call last):
  File "/Users/fusion/git/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 393, in <module>
    main()
  File "/Users/fusion/git/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 389, in main
    args.callback(args)
  File "/Users/fusion/git/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 343, in _unpack_callback
    unpack_downloads(DownloadInfo(args.ini), args.cache, args.output, extractors)
```

**Comment by Eloston** [comment]
I just added a new tag for the latest commit, which already fixes this issue.

**Comment by IvanTrendafilov** [comment]
@Eloston that build is also broken, to fix it, change these 2 lines in downloads.ini:

```
url = https://github.com/google/google-toolbox-for-mac/archive/v%(version)s.tar.gz
download_filename = v%(version)s.tar.gz
```
