### ISSUE TITLE
OSError: [Errno 66] Directory not empty

### ISSUE THREAD

**Issue by Rubyer77** [ungoogled-software/ungoogled-chromium-macos#180]
```
./build.sh
```
...
```
INFO: Unpacking "chromium" to ./ ...
Traceback (most recent call last):
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 439, in <module>
    main()
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 435, in main
    args.callback(args)
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 378, in _unpack_callback
    unpack_downloads(DownloadInfo(args.ini), args.cache, args.output, args.skip_unused, extractors)
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/downloads.py", line 341, in unpack_downloads
    extractor_func(archive_path=download_path,
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/_extraction.py", line 246, in extract_tar_file
    _extract_tar_with_tar(tar_bin, archive_path, output_dir, relative_to, skip_unused)
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/_extraction.py", line 132, in _extract_tar_with_tar
    _process_relative_to(output_dir, relative_to)
  File "/xxx/ungoogled-chromium-macos/ungoogled-chromium/utils/_extraction.py", line 87, in _process_relative_to
    src_path.rename(dest_path)
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1363, in rename
    os.rename(self, target)
OSError: [Errno 66] Directory not empty: '/xxx/ungoogled-chromium-macos/build/src/chromium-126.0.6478.61/skia' -> '/xxx/ungoogled-chromium-macos/build/src/skia'
```

**Comment by PF4Public** [comment]
Have you tried cleaning src directory?

**Comment by Cubik65536** [comment]
Delete the build directory before build.
