### ISSUE TITLE
Build fails in v8 bindings

### ISSUE THREAD

**Issue by Luka-Filipovic** [ungoogled-software/ungoogled-chromium-macos#62]
I'm always getting the same error while trying to build uc. 
Ninja updated to latest
python 2.7.18, 3.9
llvm/clang 11.0 (tried with 12.0 with no success)
xcode 12.0.1.
I even tried with windows build but its the same error.

LOG:
(large list of files from this file [here](third_party/blink/renderer/bindings/generated_in_core.gni))
python ../../third_party/blink/renderer/bindings/scripts/generate_bindings.py --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../ --root_gen_dir gen --output_core_reldir third_party/blink/renderer/bindings/core/v8/ --output_modules_reldir third_party/blink/renderer/bindings/modules/v8/ enumeration interface
Problem while looking for clang-format in Chromium source tree:
Could not find checkout in any parent of the current path.
Set CHROMIUM_BUILDTOOLS_PATH to use outside of a chromium checkout.
(previous three lines repeated like 20 times)
.
.
.
Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 100, in <module>
    main()
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 95, in main
    task_queue.run(report_progress)
  File "/Users/nikolafilipovic/Apps/ungoogled-chromium-macos/build/src/third_party/blink/renderer/bindings/scripts/bind_gen/task_queue.py", line 66, in run
    worker_task.get()  # Let |get()| raise an exception.
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeError: Style-formatting failed: filename = /Users/nikolafilipovic/Apps/ungoogled-chromium-macos/build/src/out/Default/gen/third_party/blink/renderer/bindings/core/v8/v8_text_track_mode.h
---- stderr ----
None:
[24448/43278] ACTION //third_party/blink/public/mojom:mojom_core__parser(//build/toolchain/mac:clang_x64)

_Originally posted by @Luka-Filipovic in https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/61#issuecomment-713897151_

**Comment by Luka-Filipovic** [comment]
After all dependencies update, I'm no longer getting this error
